/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fit.apcs.magicalwheel.lib;

public class SocketUtil {

    public boolean doNothing() {
        return false;
    }

}
